name: Build and Deploy Wisecow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: docker4191/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          export PATH=$PATH:/usr/local/bin
          mkdir -p ~/.kube
          if [ ! -f ~/.kube/config ]; then
           sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
           sudo chown ubuntu:ubuntu ~/.kube/config
          fi
           kubectl get nodes
           kubectl apply -f ~/assessment/k8s/deployment.yaml --validate=false
           kubectl apply -f ~/assessment/k8s/service.yaml --validate=false
